### ISSUE TITLE
Cannot resolve module 'jsx-loader'

### ISSUE THREAD

**Issue by DeepikaNR** [dlau/mineye#1]
After unzipping your folder and doing other stuff,

Did the following::
$ npm install webpack -g
$ webpack ./webpack.config.js
o/p:
 Asset     Size  Chunks             Chunk Names
all.js  1.89 kB       0  [emitted]  main
   [0] ./webpack.config.js 370 bytes {0} [built]
$ webpack 
ERROR in Entry module not found: Error: Cannot resolve module 'jsx-loader' in /Users/admin/mineye-master
$ webpack --watch

ERROR in Entry module not found: Error: Cannot resolve module 'jsx-loader' in /Users/admin/mineye-master

I might have missed something. Please help me resolve the isuue.

**Comment by dlau** [comment]
Did you do `npm  install` locally?

The front end code depends on some local npm modules.
